### ISSUE TITLE
TEXT parser out of date ?

### ISSUE THREAD

**Issue by ghost** [adutra/maven-dependency-tree-parser#3]
Hi, using the parser I get Exception at first line.
I pluged it this way :

```
Process p = Runtime.getRuntime().exec("cmd /c mvn dependency:tree", null, parent);
BufferedReader bri = new BufferedReader(new InputStreamReader(p.getInputStream()));
BufferedReader bre = new BufferedReader(new InputStreamReader(p.getErrorStream()));
InputType type = InputType.DOT;
Reader r = bri;
Parser parser = type.newParser();
try {
	Node tree = parser.parse(r);
	StandardTextVisitor visitor = new StandardTextVisitor();
	visitor.visit(tree);
	System.out.println(visitor);
				
} catch (ParseException e) {
	e.printStackTrace();
}
```
The output looks like :
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Spring Boot Tools
[INFO] Spring Boot Testing Support
[INFO] Spring Boot Loader
[INFO] Spring Boot Loader Tools
[INFO] Spring Boot Antlib
[INFO] Spring Boot Auto-Configure Annotation Processor
[INFO] Spring Boot Configuration Metadata
[INFO] Spring Boot Configuration Processor
[INFO] Spring Boot Gradle Plugin
[INFO] Spring Boot Maven Plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Tools 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.0.1:tree (default-cli) @ spring-boot-tools ---
[INFO] org.springframework.boot:spring-boot-tools:pom:2.0.0.BUILD-SNAPSHOT
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.assertj:assertj-core:jar:3.8.0:test
[INFO] +- org.mockito:mockito-core:jar:2.12.0:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.7.9:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.7.9:test
[INFO] |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] \- org.springframework:spring-test:jar:5.0.2.RELEASE:test
[INFO]    \- org.springframework:spring-core:jar:5.0.2.RELEASE:test
[INFO]       \- org.springframework:spring-jcl:jar:5.0.2.RELEASE:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot Testing Support 2.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.0.1:tree (default-cli) @ spring-boot-test-support ---
[INFO] org.springframework.boot:spring-boot-test-support:jar:2.0.0.BUILD-SNAPSHOT
[INFO] +- org.apache.maven:maven-aether-provider:jar:3.2.1:compile
...
```
Am I missing something ?
Thanks.

PS : the exception raised:
```
Exception in thread "main" java.lang.NullPointerException
	at fr.dutra.tools.maven.deptree.core.DotParser.parseFirstLine(DotParser.java:66)
	at fr.dutra.tools.maven.deptree.core.DotParser.parse(DotParser.java:49)
	at ca.umontreal.iro.logiannot.model.artefact.PomFile.executeMavenTreeDependencyCall(PomFile.java:51)
	at [...]
```

**Comment by adutra** [comment]
Hi,

You need to redirect the output to a file using `-DoutputFile=/path/to/my/file` then 

```
InputType type = InputType.TEXT;
Reader r = new BufferedReader(new InputStreamReader(new FileInputStream(...)));
Parser parser = type.newParser();
```

See [here|https://maven.apache.org/plugins/maven-dependency-plugin/tree-mojo.html] for more information.
